title: >
   <center> Nandini Ethirajulu </center>
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
   
   <center>Hi there! Iâ€™m Nandini, a passionate data professional with 6+ years of experience leveraging analytics, visualization, and predictive modeling to drive informed decisions.</center> 
  
# remote_theme: pages-themes/minimal@v0.2.0
# plugins:
#  - jekyll-remote-theme
#google_analytics: G-9GZ8BVM90K # your Google Analytics tracking ID here

#     <br>
#     Hi there! I'm Nandini, pursuing Master's in Data Science at University at Buffalo focusing on Machine Learning, Statistical Data Mining, DBMS and Analytics. 
#     <br><br>
#     <a href="https://github.com/Nandini-1312">View my Github Profile</a> 
#show_downloads: true  
theme: jekyll-theme-minimal
google_analytics: G-9GZ8BVM90K # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
