title: Nandini Ethirajulu # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
#   First description 
#   <br><br>
#   Second description 
#   <br><br>
#   <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
# remote_theme: pages-themes/minimal@v0.2.0
# plugins:
# - jekyll-remote-theme
# google_analytics: UA-000000-0 # your Google Analytics tracking ID here

  <br>
  Hi there! I'm Nandini, pursuing Master's in Data Science at University at Buffalo focusing on Machine Learning, Statistical Data Mining, DBMS and Analytics. <br><br>
  <a href="https://github.com/Nandini-1312">View my Github Profile</a> 
show_downloads: true  
